const images = [
    {src: "../../../../src/assets/EBay_logo.svg"},
    {src: "../../../../src/assets/Zenefits.svg"},
    {src: "../../../../src/assets/Compass__2_.svg"},
    {src: "../../../../src/assets/Twilio-logo-red.svg"},
    {src: "../../../../src/assets/Dropbox_logo_2017__1_.svg"},
    {src: "../../../../src/assets/Bit.ly_Logo.svg"},
    {src: "../../../../src/assets/lyft logo.svg"},
    {src: "../../../../src/assets/Loreal logo.svg"},
    {src: "../../../../src/assets/EBay_logo.svg"},
    {src: "../../../../src/assets/Zenefits.svg"},
    {src: "../../../../src/assets/Compass__2_.svg"},
    {src: "../../../../src/assets/Twilio-logo-red.svg"},
    {src: "../../../../src/assets/Dropbox_logo_2017__1_.svg"},
    {src: "../../../../src/assets/Bit.ly_Logo.svg"},
    {src: "../../../../src/assets/lyft logo.svg"},
    {src: "../../../../src/assets/Loreal logo.svg"},
    {src: "../../../../src/assets/EBay_logo.svg"},
    {src: "../../../../src/assets/Zenefits.svg"},
    {src: "../../../../src/assets/Compass__2_.svg"},
    {src: "../../../../src/assets/Twilio-logo-red.svg"},
    {src: "../../../../src/assets/Dropbox_logo_2017__1_.svg"},
    {src: "../../../../src/assets/Bit.ly_Logo.svg"},
    {src: "../../../../src/assets/lyft logo.svg"},
    {src: "../../../../src/assets/Loreal logo.svg"},
]

export default images